import { createHash } from 'node:crypto';
import { lstat, readFile, realpath } from 'node:fs/promises';
import { basename, isAbsolute, relative, resolve, sep } from 'node:path';
import fg from 'fast-glob';
import ignore from 'ignore';
import type { Ignore } from 'ignore';
import type { FileSnapshot, RepositorySnapshot } from '../core/model';
import { DEFAULT_EXCLUDES } from './exclusions';
import { classify, countLines } from './languages';
import { readGitMetadata } from './git-metadata';

export interface ScanOptions {
  gitEnvironment?: NodeJS.ProcessEnv;
  name?: string;
  exclude?: string[];
  maxFileBytes?: number;
  maxFiles?: number;
}
const hash = (content: string | Buffer) => createHash('sha256').update(content).digest('hex');
const compare = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

export async function scanLocal(
  directory: string,
  options: ScanOptions = {},
): Promise<RepositorySnapshot> {
  const root = await realpath(resolve(directory));
  if (!(await lstat(root)).isDirectory()) throw new Error('Repository input must be a directory.');
  const metadata = await readGitMetadata(root, options.gitEnvironment);
  const names = (
    await fg('**/*', {
      cwd: root,
      dot: true,
      onlyFiles: true,
      followSymbolicLinks: false,
      ignore: [...DEFAULT_EXCLUDES, ...(options.exclude ?? [])],
    })
  ).sort(compare);
  const rules: { base: string; matcher: Ignore }[] = [];

  function ignored(path: string): boolean {
    const parts = path.split('/');
    for (let i = 1; i <= parts.length; i++) {
      const prefix = parts.slice(0, i).join('/') + (i < parts.length ? '/' : '');
      let excluded = false;
      for (const { base, matcher } of rules) {
        if (!prefix.startsWith(base) || prefix === base) continue;
        const result = matcher.test(prefix.slice(base.length));
        if (result.ignored) excluded = true;
        else if (result.unignored) excluded = false;
      }
      if (excluded) return true;
    }
    return false;
  }

  // Nested rules are interpreted relative to their own directories, including negation.
  for (const path of names
    .filter((name) => name === '.gitignore' || name.endsWith('/.gitignore'))
    .sort((a, b) => a.split('/').length - b.split('/').length || compare(a, b))) {
    const parent = path.slice(0, -'.gitignore'.length);
    if (parent && ignored(`${parent}__directory_probe__`)) continue;
    const absolute = resolve(root, path);
    if ((await lstat(absolute)).isSymbolicLink()) continue;
    rules.push({
      base: path.slice(0, -'.gitignore'.length),
      matcher: ignore().add(await readFile(absolute, 'utf8')),
    });
  }
  const files: FileSnapshot[] = [];
  const skipped: RepositorySnapshot['skipped'] = [];
  for (const path of names) {
    if (ignored(path)) continue;
    const kind = classify(path);
    if (!kind) continue;
    const absolute = resolve(root, path);
    try {
      const stat = await lstat(absolute);
      if (stat.isSymbolicLink() || !stat.isFile()) {
        skipped.push({ path, reason: 'symlink or special file' });
        continue;
      }
      const actual = await realpath(absolute),
        rel = relative(root, actual);
      if (rel === '..' || rel.startsWith(`..${sep}`) || isAbsolute(rel)) {
        skipped.push({ path, reason: 'outside repository' });
        continue;
      }
      if (stat.size > (options.maxFileBytes ?? 2_000_000)) {
        skipped.push({ path, reason: 'file size limit' });
        continue;
      }
      const data = await readFile(absolute);
      if (data.byteLength > (options.maxFileBytes ?? 2_000_000)) {
        skipped.push({ path, reason: 'file size limit' });
        continue;
      }
      if (data.includes(0)) {
        skipped.push({ path, reason: 'binary content' });
        continue;
      }
      let content: string;
      try {
        content = new TextDecoder('utf-8', { fatal: true }).decode(data);
      } catch {
        skipped.push({ path, reason: 'non-UTF-8 text' });
        continue;
      }
      if (
        /^\s*(?:\/\/|#|\/\*|\*|<!--).*?(?:@generated|<auto-generated|DO NOT EDIT.{0,30}(?:generated|automatically)|generated.{0,30}DO NOT EDIT)/im.test(
          content.split(/\r?\n/).slice(0, 8).join('\n'),
        )
      ) {
        skipped.push({ path, reason: 'generated content' });
        continue;
      }
      files.push({
        path,
        ...kind,
        lines: countLines(content, kind.language),
        bytes: data.byteLength,
        contentHash: hash(data),
      });
      if (files.length > (options.maxFiles ?? 20_000)) throw new Error('SCAN_LIMIT');
    } catch (error) {
      if (error instanceof Error && error.message === 'SCAN_LIMIT')
        throw new Error(
          `Repository exceeds the ${options.maxFiles ?? 20_000} file limit; narrow the exclude configuration.`,
        );
      skipped.push({ path, reason: 'unreadable or removed during scan' });
    }
  }
  return {
    schemaVersion: 1,
    name: options.name ?? basename(root),
    source: 'local',
    ...metadata,
    snapshotHash: hash(JSON.stringify(files)),
    files,
    skipped,
  };
}
